### ISSUE TITLE
NaN in mat files are not read in as NaN but as random numbers

### ISSUE THREAD

**Issue by mivade** [pennmem/ptsa_new#16]

**Comment by maciekswat** [comment]
we agreed a long time ago not to include NaNs in Matlab. Isaac has cleaned up Ram dataset to avoid NaN's What is the point of having NaN as data?

**Comment by mivade** [comment]
I don't know who added this to the wiki or if it really matters. I doubt the numbers are actually random. Most likely, they are set to default values like -999.

**Comment by maciekswat** [comment]
They are random actually... The problem arises because in numpy when you have array of integers you cannot have NaN elements. 

A bigger problem that I see here is the inconsistency of the data stored in the matlab files. Columns lack clearly defiined types and it is very hard to interpret the values stored there. I think we should address this issue systemically and propose data formats for storing events in a way ta could be accessible by any language.

**Comment by mivade** [comment]
Closing since the original issue was not descriptive enough.
