### ISSUE TITLE
Data format for events

### ISSUE THREAD

**Issue by maciekswat** [pennmem/ptsa_new#40]
What would be best file format  for storing events? We need to move away from .mat files.  .json events are already an improvement but maybe we could do better. Any ideas?

**Comment by mivade** [comment]
Pandas DataFrames are ideal, but they are not exactly portable to different languages. However, since there is nice support for a variety of formats, this is a minor problem. I like SQLite a lot for things like this.

**Comment by ctw** [comment]
What's wrong with json?

**Comment by mivade** [comment]
JSON can be good as an interchange format, but it has some disadvantages:

- It encourages nesting (luckily we aren't doing too much of this right now)
- It has no support for defining schemas, which can lead to data quality issues if people aren't careful to be consistent
- It can't be appended to since it must start and end with curly braces. This is particularly annoying in Ramulator when we are writing events.

Theoretically there is such a thing as [JSON schema](http://json-schema.org/), but that's an optional thing that not everyone would necessarily be using. Something like SQLite or HDF5 tables, on the other hand, would strongly mandate data types and have other advantages like built-in support for advanced querying.

**Comment by maciekswat** [comment]
I think enforcing data types should help with portability. Since hdf5 has anice browser this could be a viable option. The only issue is the way it stores unicode - some legwork would be necessary. Would SQLLite be easily accessible from Matlab? We need to take this factor into account as well...

**Comment by mivade** [comment]
Looks like Matlab has built-in support for SQLite: https://www.mathworks.com/help/database/ug/sqlite-object.html;jsessionid=c33d2a8a9a7e441f132633f15230

Unicode is not too difficult to handle, but it does require explicitly doing things like `string.encode()` a lot. One annoying thing about HDF5 for string data when using a table is that (as far as I know), you have to allocate a fixed space for string columns. This means we would have to err on the side of too long, which also means that the size on disk of the file will be larger than necessary (probably not a big deal, though).

I think I prefer SQLite for this, but HDF5 would also be fine. SQLite does also have a better [browser](http://sqlitebrowser.org/) than HDF5's. Users wouldn't even need to learn SQL (though they should because SQL makes you a better person) since pandas can read SQL trivially, e.g.:

```python
import sqlite3
import pandas as pd

with sqlite3.connect("events.sqlite") as db:
    df = pd.read_sql("events", db)
```

One final advantage to SQL over HDF5: while we could start by using SQLite, if we wanted to later transition to a real database (as opposed to just storing files in a directory structure like we do now), very little would need to change on the analysis side. For example, if we used postgres, the above code would just need to be modified to point to that database instead of the SQLite file:

```python
import sqlalchemy as sa

engine = sa.create_engine('postgresql://user:password@host/eventsdb')
df = pd.read_sql("events", engine)
```

**Comment by mivade** [comment]
Also relevant for converting between various formats: [odo](https://odo.readthedocs.io/en/latest/)

**Comment by mivade** [comment]
I've put together a small demo [here](https://github.com/pennmem/sqlevents) of using SQL for storing events. It includes a (work in progress) conversion from JSON events.

**Comment by mivade** [comment]
Closing this discussion for now since there has not been any signs of a desire to overhaul our existing data storage format. Feel free to reopen later.
