### ISSUE TITLE
RAM data tutorial is incomplete

### ISSUE THREAD

**Issue by smeisler** [pennmem/ptsa_new#48]
When I try to create the Json Reader as instructed in the tutorial,

>>> jr = JsonIndexReader('/protocols/r1.json')

I receive the following error:

'JsonIndexReader is not defined'

I tried importing JsonIndexReader directly from ptsa and the module cannot be found.

**Comment by mivade** [comment]
Which tutorial are you looking at? If you're looking on readthedocs, that is now outdated. Instead look at the updated documentation [here](https://pennmem.github.io/ptsa/index.html). However, it looks like the tutorial doesn't explicitly show where you should be importing that:

```python
from ptsa.data.readers.IndexReader import JsonIndexReader
```

I've also just commited a change so that  in the next release you will be able to simplify this to:

```python
from ptsa.data.readers import JsonIndexReader
```
